on:
  push:
    branches:
      -develop
name: Deploy via ftp
jobs:
  deploy:
    name: Deploy
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: Use Node.js 18
      uses: actions/setup-node@v2
      with:
        node-version: '18'
      
    - name: Build Project
      run:
        npm install
        npm run build
    
    - name: List output files
      run: find build/ -print

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST }} 
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        localDir: "public_html/staging"