name: Deploy via ftp

on:
  push:
    branches: ["develop"]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: 18

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js 18
      uses: actions/setup-node@v3
      with:
        node-version:  18
        cache: 'npm'
    - run: npm ci
    - run: npm run build --if-present
    - run: npm test
    
    - name: List output files
      run: find build/ -print

    - name: FTP Deploy Locaweb
      uses: locaweb/ftp-deploy@1.0.0
      with:
        host: ${{ secrets.HOST }} 
        user: ${{ secrets.USER }}
        password: ${{ secrets.PASSWORD }}
        localDir: "public_html/staging"